### ISSUE TITLE
eMoflon::IBeX 2.0: Release TODO collection

### ISSUE THREAD

**Issue by maxkratz** [eMoflon/emoflon-ibex#424]
This issue should be used to collect TODOs for the release of eMoflon::IBeX 2.0.

### TODOs (bugs, features, etc.)

I included all of the TODOs of my notes in the following list:

- [x] There are two failing tests (as of today = 2024-04-24):
  - [this commit](https://github.com/eMoflon/emoflon-ibex/commit/b4a79e902cb037c458c538b74be3018c53b8dc28) resolved the issue

![image](https://github.com/eMoflon/emoflon-ibex/assets/20956405/79930056-0dd3-4f67-8e95-03ba489c9ac7)

- [x] One of the TGG-related projects is broken after the dev checkout (as of today = 2024-04-24):
  - As far as I can see, there is no `xtend-gen` folder in the project but there are also no `xtend` files -> maybe this is just a buildpath problem. 
  - Update: it was just a classpath problem and I [fixed it](https://github.com/eMoflon/emoflon-ibex-ui/commit/69a34bdf2380f3ad9e19995009649d962e611928).

```
Description	Resource	Path	Location	Type
Project 'org.emoflon.ibex.tgg.tggl.ui' is missing required source folder: 'xtend-gen'	org.emoflon.ibex.tgg.tggl.ui		Build path	Build Path Problem
```

- [x] PlantUML visualization is currently broken (is it?)
  - [x] TGGL visualization is broken -> the TGGL visualization is fine, see update comment below.
  - [x] GTL visualization is a TODO
- [x] Update site build is broken -> fixed
- [x] MWE2 configs for a complete dev build -> done
- [ ] IBeX: Update all version numbers to v2.x.x -> Max already started this on separate branches?
  - Max: We should only update all version numbers of projects we touched during the development of IBeX 2.0.
  - Some of the projects (e.g., in the emoflon-core repo) already have version numbers >2.0.0.
- [x] HiPE: Update all version numbers to v2.x.x -> Max already started this on an extra branch
- [ ] Tutorial seems to be broken. The tutorial should be working before releasing IBeX v2.x.
  - [x] Remove all `count()` operator-related code snippets and text from the tutorial.
  - Current state: HiWi is working on it.
- [x] IBeX 2.0 should be runnable with the latest Eclipse release -> tested and verified with the 2024-03 release by Max.
- [x] `README.md` + installation instruction must be updated
- [x] PSF dev must be updated/fixed
- [x] PSF test must be updated/fixed
  - [x] As with the IBeX v1 test workspace, we should provide different PSF files for {all projects, GT-only, TGG-only}.
- [x] Update all branches before merging -> was at least done once by Max
  - [ ] Before finally merging all branches, we [Max?] should check it again
- [x] `org.apache.commons.io` is missing in the UI project -> fixed
- [x] Migrate the Xtext bugfix for `IQualifiedName` -> done
- [x] Fix test case `Multiplicity` -> test was successful with a new dev workspace and HiPE stateless -> done
- [x] Remove/delete old unused projects (GT editor, TGG editor, etc.) -> seems to be done?
- [x] Create Wizards (2x) for TGG -> done by Lars
  - [x] TODO(Max): check and verify them -> both are fine
  - [x] `DefaultFilesHelper`: remove [typo](https://github.com/eMoflon/emoflon-ibex/blame/refactoring/rework_TGG/org.emoflon.ibex.tgg.compiler/xtend-src/org/emoflon/ibex/tgg/compiler/codegen/DefaultFilesHelper.xtend#L27) (`#`)
- [x] Integrate the TGG Wizards into the upper menu bar -> Update: after including the new tgg wizards project, the upper menu bar seems to be fine.

IBeX v1.x:
![image](https://github.com/eMoflon/emoflon-ibex/assets/20956405/8f08e4cb-5166-4efe-8619-ac8ac5686681)

IBeX v2.x (as of 2024-04-25):
![image](https://github.com/eMoflon/emoflon-ibex/assets/20956405/90ca77ac-9e8e-4496-b2f1-ce5811cadfb1)

- [x] Delete old/irrelevant projects from the repositories.
  - [x] `org.emoflon.ibex.tgg.editor` on https://github.com/eMoflon/emoflon-ibex-ui/tree/rework_TGG_validatorfix
  - [x] `org.emoflon.ibex.ide.democles.feature`?
  - [x] `org.emoflon.ibex.tgg.editor.feature`?
  - `org.moflon.core.tycho.parent`? -> nope, I do not touch this
  - `org.moflon.releng.p2`? -> nope, I do not touch this
- [x] HiPE stateless in IBeX 1.0 generates non-compilable code
  - HiPE stateless is not compatible with IBeX 1.0 -> "done"
- [x] Push the IBeX-related tests with commented-out `count()` operator -> done
- [x] Find a way to release HiPE v1.x and HiPE v2.x on the same update site without creating merge conflicts every time
  - Currently on Max's TODO list.
- [ ] HiPE: Deploy new update site build for v1 & v2 (see https://github.com/eMoflon/emoflon-ibex/issues/424#issuecomment-2079279813)
- [x] Find a way to release IBeX v1.x and IBeX v1.x on the same update site without creating merge conflicts every time
  - As with the same issue with HiPE, we have to find a solution.
- [ ] IBeX: Deploy new update site build for v1 & v2 (see https://github.com/eMoflon/emoflon-ibex/issues/424#issuecomment-2079279813) 
- [ ] HiPE 2.0: Create detailed documentation/instructions on how to release v1.x and v2.x
- [ ] HiPE 2.0: Adapt scripts for building the update site and remove `Democles` from them
- [ ] HiPE: Update the PSF file for v2.x.
- [ ] IBeX Eclipse builds: Find a way to release v1.x and v2.x in parallel. (This should be easier as the issue with the update site(s).)
- [ ] IBeX VM builds: Find a way to release v1.x and v2.x in parallel. (See Eclipse-related TODO above.)
- [x] IBeX tests: All launch config files with `Democles` should be removed -> done + removed further Viatra artifacts.
- [ ] Remove Democles artifacts in all IBeX-related repositories (e.g., in the `site.xml` config of the update site).
- [x] Update IBeX v2 to JDK21
- [x] Update HiPE v2 to JDK21
- [x] Update IBeX v2 tests to JDK21
- [x] Merge the fix for the `JavaVersionHelper` in `emoflon-core` from `master` into the feature branch

### Releasing itself

When all TODOs/blocking bugs, etc. are resolved, these are the steps we should take to make the final release happen:

- [x] Create and collect all related PRs to this issue.
- [ ] Tag and push the old version (1.x.x) in every IBeX repo + tutorial repo + test repo
- [ ] Release another IBeX v1.x with HiPE v1.x (Max can do it)
  - [ ] Update site
  - [ ] Eclipse
  - [ ] VM
- [ ] Release HiPE v2.x (stateless) to its update site.
- [ ] Merge all IBeX 2.0-related PRs.
- [ ] Merge the [tutorial branch](https://github.com/eMoflon/emoflon-ibex-tutorial/tree/new-tgg-and-gt) for IBeX 2.0.
- [ ] Tag and release a new version of the tutorial to trigger a PDF build.
- [ ] Merge `emoflon-ibex-test` branch(es) for IBeX 2.0.
  - [ ] [rework_TGG](https://github.com/eMoflon/emoflon-ibex-tests/tree/rework_TGG)
  - [ ] [newHiPETests](https://github.com/eMoflon/emoflon-ibex-tests/tree/newHiPETests)?
    - AFAIK, the test implementation is not completed, yet.
  - [ ] [feature/higher-order-ilp](https://github.com/eMoflon/emoflon-ibex-tests/tree/feature/higher-order-ilp)?
  - [ ] [feature/new-pm-tests](https://github.com/eMoflon/emoflon-ibex-tests/tree/feature/new-pm-tests)
- [ ] Release IBeX v2.x with HiPE v2.x = stateless (Max can do it)
  - [ ] Update site
  - [ ] Eclipse
  - [ ] VM
- [ ] Update the https://emoflon.org website to include instructions for IBeX v1 and IBeX v2.

### Afterwards

- [ ] Open (an) issue(s) for the missing features of the GT(L) visualization
- [ ] We should enforce a common code style.
  - I [Max] moved this from the "before releasing" to "afterwards" because we do not want to have touched every file in all PRs for the release.
- [ ] Enforce a common code style / organize all imports on all projects

**Comment by Arikae** [comment]
Regarding the first point, I thought the GTL vis is not broken but just no longer supported.

**Comment by maxkratz** [comment]
> > Regarding the first point, I thought the GTL vis is not broken but just no longer supported.

> As far as I can see, both, the TGGL and the GTL visualization are currently broken/not supported.

Nope, I was wrong. The TGGL visualization is fine on my test system.

**Comment by maxkratz** [comment]
I updated the list above with these TODOs:

- Update the version numbers of all IBeX-related projects & HiPE-related projects to v2.x.x.
- Suggestion to enforce a common code style before merging everything.
- HiPE: Update the PSF file
- A `tggl.ui` project has an error after checkout
- IBeX tests: Remove all `Democles` launch files
- Two IBeX tests are currently broken
- PlantUML: Visualization of GTL + TGGL is broken/not supported

**Comment by maxkratz** [comment]
~~Update: I added a TODO:~~
- ~~Integrate both of the new TGG wizards into the upper Eclipse menu bar~~

Update for the update: after adding the new TGG wizard project to my dev WS, the upper menu bar seems to be fine.

**Comment by maxkratz** [comment]
Update: Both TGG wizards work as expected.

**Comment by maxkratz** [comment]
Update on the TGG project build error after checkout:

> - [x] One of the TGG-related projects is broken after the dev checkout (as of today = 2024-04-24):

It was just a classpath problem and I [fixed it](https://github.com/eMoflon/emoflon-ibex-ui/commit/69a34bdf2380f3ad9e19995009649d962e611928).

**Comment by maxkratz** [comment]
Update:

> - [x] There are two failing tests (as of today = 2024-04-24):
 
Fixed by [this commit](https://github.com/eMoflon/emoflon-ibex/commit/b4a79e902cb037c458c538b74be3018c53b8dc28).

**Comment by maxkratz** [comment]
Update regarding the update site releasing of HiPE v1/v2 and IBeX v1/2:

As @Arikae and I found today, we have two ways to get around the problem of how to release v1 and v2 on one update site:

### 1. Rebuild the whole update site for every release
- This means we would have to build X v1 and v2 from scratch, delete all previous releases of X from the update site (as we do it now, we just wipe the whole update site), and rebuild the site.
- **Pro**: the current structure of the update site project etc. could stay almost the same
- **Con**: one has to build both versions for a release (that does not make any sense IMO)

### 2. Move the update site project to its own repository
- Move the update site project to its own repository and add releases of X v1 and v2 when they appear.
- **Pro**: one has only to build the product (v1 or v2) that they want to release right now.
- **Con**: because of the (incremental) update site build process, we can not delete previous releases that easily.
  - Currently, the only workaround that we see for deleting previous releases would be option no. 1 (see above).
- One could argue that the git repository will grow in size for each new release because older releases will not be removed. That is correct (at least if I understand it correctly) but this should also be the case for our current approach for wiping and recreating the update site for every new build because the diffs are kept by git anyway.
  - That is why our current git repository for the update site is >900 MB (!) in size.
- Another TODO for this approach would be to completely ditch the update site repo (*not the project!*) and commit the JAR artifacts directly to the update site *project*. The project needs the information/artifacts of the previous builds to update the update site incrementally.
  - I can adapt the GitHub Action publishing the update site etc, this is not a problem :).

**Comment by maxkratz** [comment]
Update: Unused/old projects/artifacts removed (besides the moflon-core tycho-related projects).

**Comment by maxkratz** [comment]
Summary of all IBeX v2 related pull requests:

HiPE:
- https://github.com/HiPE-DevOps/HiPE/pull/20

eMoflon development workspace:
- https://github.com/eMoflon/emoflon-core/pull/151
- https://github.com/eMoflon/emoflon-ibex-ui/pull/216
- https://github.com/eMoflon/emoflon-ibex-hipe/pull/5
- https://github.com/eMoflon/emoflon-ibex-deployment/pull/7
- https://github.com/eMoflon/emoflon-ibex/pull/425

eMoflon test workspace:
- https://github.com/eMoflon/emoflon-ibex-tests/pull/116

**Comment by maxkratz** [comment]
I've upgraded all projects (IBeX v2 dev, HiPE v2 (stateless) dev, and IBeX v2 tests) to JDK21 (via merging the `master`/`main` branches and fixing all resulting errors).

**Comment by maxkratz** [comment]
I've ported all recent changes in HiPE + eMoflon IBeX GT v1 to the v2 branches.
- HiPE path options
- IBeX API initialization with a given pattern path (instead of using the hard-coded paths determined during project compilation)
